const menu = [
    {
        id: 1,
        title: 'Serpme Kahvaltı (2 kişilik)',
        category: 'breakfast',
        price: 100,
        img: './images/breakfast-1.jpg',
        desc: `Ezine beyaz peynir, çikolata, tahin & pekmez, kaymak, süzme bal & tereyağı, siyah ve yeşil zeytin, sosis şiş, sahanda yumurta, pişi, yumurtalı ekmek, meyve salatası ve 2 kişi için sınırsız çay ile `,
    },
    {
        id: 2,
        title: 'Tost',
        category: 'breakfast',
        price: 25.99,
        img: './images/breakfast-2.jpg',
        desc: `Domates ve beyaz peynir ile `,
    },
    {
        id: 3,
        title: 'Hamburger',
        category: 'lunch',
        price: 6.99,
        img: './images/lunch-1.jpg',
        desc: `Burger köftesi (180gr), burger sos, cheddar peyniri, kremalı mantarlı ılık sos, çıtır soğan, patates tava`,
    },
    {
        id: 4,
        title: 'Tavuk Dürüm',
        category: 'lunch',
        price: 50.99,
        img: './images/lunch-2.jpg',
        desc: `Sotelenmiş tavuk bonfile dilimleri, mantar, cheddar peyniri, soğan, renkli biberler, patates tava `,
    },
    {
        id: 5,
        title: 'Kebap',
        category: 'lunch',
        price: 99.99,
        img: './images/lunch-3.jpg',
        desc: `Yufkaya sarılı ev yapımı köfte, çörek otlu cacık, sote sebzeler, patates tava, ızgara domates ve biber ile `,
    },
    {
        id: 6,
        title: 'Makarna',
        category: 'lunch',
        price: 45.99,
        img: './images/lunch-4.jpg',
        desc: `Kıymalı bolognese sos, pesto sos, sarımsak ve parmesan ile`,
    },
    {
        id: 7,
        title: 'Pizza',
        category: 'lunch',
        price: 79.99,
        img: './images/lunch-5.jpg',
        desc: `Mozzarella, domates sos, sucuk, jalapeno biber, yeşil zeytin, yeşil biber, domates `,
    },
    {
        id: 8,
        title: 'Bira',
        category: 'drink',
        price: 49.99,
        img: './images/drink-1.jpg',
        desc: `50cl - Beck's, Miller, Bud, Corona, Guinness, Efes Özel Seri, Bomonti  `,
    },
    {
        id: 9,
        title: 'Kokteyl',
        category: 'drink',
        price: 110.99,
        img: './images/drink-2.jpg',
        desc: `Tequila, portakal likörü, margarita mix Klasik / Meyveli.`,
    },
];

export default menu;